### ISSUE TITLE
Ability to install multiple version

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/OpenShift#208]
Today, ARO supports two OpenShift versions at any point in time, but only supports the creation of clusters using the latest supported OpenShift version. This issue tracks a feature that allows you to specify an OpenShift version when creating an ARO cluster.

**Comment by siw36** [comment]
Hi, we're currently in the process of rolling out multiple ARO clusters and are now heaving trouble because this feature is missing.
We already created two clusters with version 4.6 and have committed to this version for all of the clusters we are creating the following days/weeks. We did this to simplify the upgrade process of the mentioned clusters and to have the same base version for all of our workloads.

But I will now get a 4.7 ARO cluster when creating one, so our cluster versions will differentiate throughout this rollout phase. This means more work for me and my team to get all clusters to the same version again.

I would really appreciate this feature as soon as possible.

**Comment by marcusne** [comment]
Same to me, it's mandatory for us to maintain that all ARO clusters, existing ones and newly created once are version aligned, so I would be happy to see this implemented as well.

**Comment by DaveSpe** [comment]
+1 same here, need this feature asap.

**Comment by msftnadavbh** [comment]
I have multiple customers requesting this feature. Any update?

**Comment by wilfredjamison** [comment]
Some products, such as Cloud Paks from IBM, that run on top of OpenShift are not necessarily in syched with the latest version of OpenShift. They may be 1 minor version behind because they cannot test the new OCP version ahead of time before it gets released. 

Having said that, this introduces a major problem when a customer wants to use a Cloud Pak product on ARO. The ability to specify an older version is a major need in this use case, or this will cause a customer to drop ARO as an option since ARO is not the only way that the Cloud Pak products can be deployed. Microsoft may be losing revenues if you don't support this scenario.

**Comment by TiloGit** [comment]
this severely limits us. We use that to create Non-PRD cluster and PRD cluster (with month in between). How to create a new temp cluster (old version) to test upgrade.

creating a bunch of ARO cluster at Day one is cost prohibitive. 

**AKS supports this via:** ```--kubernetes-version```


@wilfredjamison fyi, We are also working to setup IBM CP on ARO.

**Comment by dcaldwel** [comment]
> 

I also have a customer who has requested this feature. From a security, compliance and testing POV, I imagine that if you spend x weeks getting your test environment certified only to find out that you can no longer roll out the same version for a prod environment, it may be a little frustrating.

**Comment by joharder** [comment]
This feature is currently in development, however there is not yet a firm ETA to share.

**Comment by miroag** [comment]
:+1:

**Comment by GijsvanDulmen** [comment]
Would there be an ETA already? We also want the ability to install some other version like 4.8 when 4.9 is the current default.

**Comment by Ashengross** [comment]
any updates on timeline? we have few requirements from customer for it

**Comment by lhoss** [comment]
Same here, we need to install OCP 4.8 (since OpenDatahub.io is not yet ready for later versions).
Frankly quite unbelievable for me this >1y old and often requested feature  hasn't been implemented yet!
(compare that to AWS OpenShift "ROSA" installer `rosa create cluster --version "4.8.34" ...`!)
First saw the feature is missing, by checking https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest#az-aro-create

### Workaround ?!
However the installation via ARM/BICEP Template seems to support giving the cluster version .. (even though the field is not exposed as a template parameter) , via the `clusterProfile/version` field:
Ref: https://docs.microsoft.com/en-us/azure/templates/microsoft.redhatopenshift/openshiftclusters?tabs=json
But is this working at all ?
( I'ld prefer to use `az aro` though )

**Comment by jasonvriends** [comment]
I would love to see this also.

**Comment by mayankarora-ibm** [comment]
Any update on the timeline for this?

**Comment by MichaelWasher** [comment]
When this does get implemented, can we make sure that the Z-stream can also be configured?

**Comment by joharder** [comment]
> ### Workaround ?!
> However the installation via ARM/BICEP Template seems to support giving the cluster version .. (even though the field is not exposed as a template parameter) , via the `clusterProfile/version` field: Ref: https://docs.microsoft.com/en-us/azure/templates/microsoft.redhatopenshift/openshiftclusters?tabs=json But is this working at all ? ( I'ld prefer to use `az aro` though )

This will not work. It's only possible right now to install the current latest version. I'm working with the PM team to see if they have an ETA yet that we can share.

**Comment by dcaldwel** [comment]
Is there any ETA on this feature being incorporated?

**Comment by yongkanghe** [comment]
Surprises, there is no way to specify the version. Adding _**--version 4.x**_ should not take a year or more?

**Comment by jboutaud** [comment]
This feature is now live for customers and customers can use the --version flag in the CLI to specify a version to deploy

**Comment by mosabami** [comment]
now GA

https://learn.microsoft.com/en-us/azure/openshift/tutorial-create-cluster
https://learn.microsoft.com/en-us/azure/openshift/support-lifecycle
