### ISSUE TITLE
Another object with the same value for property identifierUris already exists.

### ISSUE THREAD

**Issue by jim-minter** [Azure/OpenShift#34]
If you use `az openshift create` and let it create your AAD app, then use `az openshift delete`, then do another `az openshift create` with the same name, you get the error `Another object with the same value for property identifierUris already exists.`

I'm not immediately sure what the right route to improve this is, but it definitely needs improvement.

**Comment by jim-minter** [comment]
@julienstroheker ptal

**Comment by julienstroheker** [comment]
@jim-minter the reason is we are not deleting the AAD app previously created.

I can print the warning `Another object with the same value for property identifierUris already exists.` + something like `Please contact the owner to manually update it or specify another AAD App using the aad-app-id and aad-app-password options`

What do you think ?

**Comment by jim-minter** [comment]
Another alternative is an additional CLI option `--try-to-update-aad-application-uri-if-app-already-exists`.  This might update the AAD application return URL if appropriate and would generate and fetch a new AAD app secret for use by OSA.

**Comment by julienstroheker** [comment]
CLI has been updated. The `create` command should automatically update the AAD app if it already exists.
@jim-minter if you can run some tests on your side to validate it, it will be appreciated.
Thanks

**Comment by julienstroheker** [comment]
Closing for now, should be fixed. Feel free to re-open if you still seeing this.
