### ISSUE TITLE
New resource group is created during installation

### ISSUE THREAD

**Issue by dcfsc** [Azure/OpenShift#55]
I created resource group prdusefssocpdemorg
Then create:
```
CLUSTER_NAME=fssocpdemo
RESOURCE_GROUP_NAME=prdusefssocpdemorg
LOCATION=eastus
az openshift create --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME -l $LOCATION --fqdn $FQDN 
```
This created a cluster but in a new resource group called "914a092f-ebca-4ccb-XXa4-XXXXX".

I expected all the new resources to be created in the existing RG `prdusefssocpdemorg`, but it is empty.

If this is expected behavior, what is the point of supplying the resource group?

**Comment by julienstroheker** [comment]
Hi @dcfsc 

This is the expected behavior, in your RG `prdusefssocpdemorg` you can tick the `Show hidden types` option and see the `Microsoft.ContainerService/openShiftManagedClusters` resource.

The GUID RG `914a092f-ebca-4ccb-XXa4-XXXXX` is your managed cluster. 
It's a locked RG managed by RedHat and Microsoft to guarantee the quality of service.

Hope this makes sense.

**Comment by sakthi-vetrivel** [comment]
Closing this issue as it's gone stale.
