### ISSUE TITLE
Master nodes have public IP address and they are reachable with SSH

### ISSUE THREAD

**Issue by tahonen** [Azure/OpenShift#67]
Noticed that master node instances have public IP addresses and they are accessible via SSH. I don't have key or password to login, but due some vulnerability or config failure "wrong" user may get access to machine. In case Openshift vnet is peered with some on-prem transit vnet, this user might get access to on-prem network.

**Comment by amanohar** [comment]
Thanks @tahonen for the input.

Regarding:
>IMHO masters do not need public IPs
At this time this is by design.

We can consider improvements to further lock down SSH access. One thing to note here is that in the current architecture customer will not be able to generate SSH keys. But like you mention a future unknown bug could be a concern and access should be restricted.

**Comment by amanohar** [comment]
SSH is now locked down.
